apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Sepulsa Frontend
  description: A Frontend for Sepulsa
  tags:
    - java
    - data
  links:
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/admin
      title: Admin page
      icon: user
    - url: https://example.com/dashboard
      title: Observability Dashboard
      icon: dashboard
    - url: https://github.com/
      title: GitHub Repo
      icon: github
spec:
  type: website
  lifecycle: production
  owner: Tegar Imansyah
  system: sepulsa
  dependsOn: 
    - 'resource:sepulsa-db'
    - 'resource:sepulsa-cache'
  providesAPIs:
    - sepulsa-api

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sepulsa-db
  description: PostgreSQL 14
spec:
  type: database
  system: sepulsa

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sepulsa-cache
  description: Redis 5
spec:
  type: database
  system: sepulsa
